{{- if .Values.studio.enable -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supabase.studio.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  {{- if not .Values.studio.autoscaling.enabled }}
  replicas: {{ .Values.studio.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "supabase.studio.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.studio.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "supabase.studio.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.studio.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "supabase.studio.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.studio.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "supabase.studio.name" $ }}
          securityContext:
            {{- toYaml .Values.studio.securityContext | nindent 12 }}
          image: "{{ .Values.studio.image.repository }}:{{ .Values.studio.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.studio.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.studio.environment }}
            - name: {{ $key }}
              valueFrom:
                configMapKeyRef:
                  name: {{ include "supabase.studio.fullname" $ }}
                  key: {{ $key }}
            {{- end }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            {{- toYaml .Values.studio.resources | nindent 12 }}
      {{- with .Values.studio.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.studio.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.studio.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}