apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supabase.kong.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  {{- if not .Values.kong.autoscaling.enabled }}
  replicas: {{ .Values.kong.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "supabase.kong.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.kong.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "supabase.kong.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.kong.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "supabase.kong.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.kong.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "supabase.kong.name" $ }}
          securityContext:
            {{- toYaml .Values.kong.securityContext | nindent 12 }}
          image: "{{ .Values.kong.image.repository }}:{{ .Values.kong.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.kong.image.pullPolicy }}
          volumeMounts:
            - name: config-volume
              mountPath: /var/lib/kong/kong.yml
              subPath: kong.yml
          env:
            {{- range $key, $value := .Values.kong.environment }}
            - name: {{ $key }}
              valueFrom:
                configMapKeyRef:
                  name: {{ include "supabase.kong.fullname" $ }}
                  key: {{ $key }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            {{- toYaml .Values.kong.resources | nindent 12 }}
      {{- with .Values.kong.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kong.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kong.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "supabase.kong.fullname" $ }}
            items:
            - key: kong.yml
              path: kong.yml
